cat > .github/workflows/basic-ci.yml << 'EOF'
name: Basic Python CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pytest
        run: pip install pytest

      - name: Run script
        run: python app.py
EOF

